### ISSUE TITLE
If hovering a pintab, the number doesn't show, and that leads to EnterPin failing!

### ISSUE THREAD

**Issue by NicklasSoderberg** [Elfyyy/OSR-Reflection#26]
If hovering a pintab, the number doesn't show, and that leads to EnterPin failing!

**Comment by FittaVillavu** [comment]
WithdrawBankItem fails when trying to enter a number and another number already exists but is greater.

1
14

I entered 1 for amount, but it keeps choosing 14.

Simple fix -> Add a ' ' space after the IntToStr(Amount) + ' '   <--

**Comment by FittaVillavu** [comment]
NPC.IsMoving?

Is it possible to make Actor have isMoving?

**Comment by FittaVillavu** [comment]
Actor.UnderAttack should totally be a thing too!
