### ISSUE TITLE
Actor -> UnderAttack & IsMoving

### ISSUE THREAD

**Issue by NicklasSoderberg** [Elfyyy/OSR-Reflection#28]
Could we have those added to Actor instead of LocPlayer only? Would make a huge difference is some cases.

**Comment by KyleHunter** [comment]
Wonder why I did that :/

**Comment by akarigar** [comment]
Looks like `IsMoving` is already in `TReflectActor`. I'm also renaming `UnderAttack` to `IsUnderAttack`.
