### ISSUE TITLE
Make a static `Reflect.Inv` for essential inventory functionality.

### ISSUE THREAD

**Issue by akarigar** [Elfyyy/OSR-Reflection#33]
Need to include:
- `Reflect.Inv.Contains(TheItem: Variant)`
- `Reflect.Inv.Count`
- `Reflect.Inv.Count(TheItem: Variant)`
- `Reflect.Inv.Get`
- `Reflect.Inv.Get(TheItem: Variant)`
- `Reflect.Inv.GetAll`
- `Reflect.Inv.GetAll(TheItem: Variant)`
- `Reflect.Inv.IsEmpty`
- `Reflect.Inv.IsFull`

**Comment by akarigar** [comment]
This should also close out #29.

**Comment by akarigar** [comment]
Need to put this back in with a warning in the deprecated methods.

**Comment by KyleHunter** [comment]
Yeah

**Comment by TheTS** [comment]
Might as well add:

Reflect.Inv.Drop(TheItem: Variant); 
Reflect.Inv.DropAll();

something like:

``` pascal
procedure TReflectInvItemArray.dropAll();
var
  i: Integer;
begin
  // We should have self.isEmpty() too

 Self.GetAll();

  for i := 0 to high(Self) do
  begin
    Self[i].Click(MOUSE_RIGHT);
    Reflect.Text.ChooseOption('Drop');
  end;
end;
```
