### ISSUE TITLE
ID Debugging

### ISSUE THREAD

**Issue by TheTS** [Elfyyy/OSR-Reflection#37]
Would be awesome to have SMART debugging for IDs for:

TReflectNPC
TReflectObject

Something like: 
![27zf4g5](https://cloud.githubusercontent.com/assets/8165365/5951176/59bb5d3c-a7c8-11e4-92b7-a16a8bce8a4d.png)

**Comment by KyleHunter** [comment]
Someone should work on this, I'm too busy currently

**Comment by TheTS** [comment]
I've pretty much done it already, just need to clean it up for the include.
