### ISSUE TITLE
New functions

### ISSUE THREAD

**Issue by TheTS** [Elfyyy/OSR-Reflection#47]
Functions to make it easier to interact with NPC/Objects/GroundItems

.RotateTo
.IsOnMS
.WalkTo

E.g.:

``` pascal
procedure TReflectNPC.RotateTo();
begin
  Reflect.Tiles.RotateCameraToTile(Self.GetTile);
end;

function TReflectNPC.IsOnMS(): Boolean;
begin
  Result := PointInBox(Self.GetMSPoint, IntToBox(4, 4, 515, 337));
end;

procedure TReflectNPC.WalkTo();
begin
  MyPlayer.WalkToTileMM(Self.GetTile); //Not sure how you would make this global
end; 
```

and then we can do stuff like:

``` pascal
  if not Goblin.isOnMS() then
  begin
    Goblin.WalkTo();
    Goblin.RotateTo();
  end;
```

So you can walk to the NPC and then rotate the camera to center it on screen while still moving towards it :)

**Comment by michaelmob** [comment]
I've added these functions in the pull request below
https://github.com/Elfyyy/OSR-Reflection/pull/58

**Comment by KyleHunter** [comment]
Am not going to add these for the time being due to being able to use another function for them already.
e.g:  Reflect.Tiles.Rotate(Npc.GetTile) LocPlayer.BlindWalkMM(Npc.Tile);

**Comment by TheTS** [comment]
Yea we can just do it the other way then. It will be good to add the .IsOnMS though, so you dont have to call PointInBox each time. I will send in a separate pull request for those
